# AWS SAM template for SecurityHub SOC 2 Compliance Analyzer
# This template creates an automated solution for analyzing SecurityHub findings
# and mapping them to SOC 2 controls. The solution includes:
# - Lambda function for analyzing findings and generating reports
# - S3 bucket for storing analysis reports
# - EventBridge rule for scheduled execution
# - Required IAM permissions and security configurations

AWSTemplateFormatVersion: '2010-09-09'
Description: 'SecurityHub SOC 2 Compliance Analyzer - Automatically maps SecurityHub findings to SOC 2 controls'

# Template Parameters
# These parameters allow customization during deployment
Parameters:
  # Email configuration for report delivery
  SenderEmail:
    Type: String
    Description: Email address to send reports from (must be verified in SES)
  
  RecipientEmail:
    Type: String
    Description: Email address to send reports to
  
  # Configuration for the analysis time window
  FindingsHours:
    Type: Number
    Default: 24
    Description: Number of hours of findings to analyze
    MinValue: 1
    MaxValue: 168  # Maximum 1 week of findings

# AWS Resources created by this template
Resources:
  # Main Lambda Function Resource
  # This function performs the core analysis and reporting logic
  SecurityHubSOC2AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./  # Points to the directory containing the Lambda code
      Handler: index.lambda_handler  # Entry point for the Lambda function
      Runtime: python3.9
      Timeout: 300  # 5 minutes to allow for AI processing
      MemorySize: 512  # Increased memory for handling large datasets
      
      # Environment variables used by the Lambda function
      Environment:
        Variables:
          SENDER_EMAIL: !Ref SenderEmail
          RECIPIENT_EMAIL: !Ref RecipientEmail
          FINDINGS_HOURS: !Ref FindingsHours
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
      
      # IAM permissions required by the Lambda function
      Policies:
        - Version: '2012-10-17'
          Statement:
            # SecurityHub permissions for reading findings
            - Effect: Allow
              Action:
                - securityhub:GetFindings
                - ses:SendRawEmail
                - bedrock:InvokeModel
              Resource: '*'
            
            # S3 permissions for report storage
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub '${ReportsBucket.Arn}/*'

  # S3 Bucket for Report Storage
  # This bucket stores the generated analysis reports with security configurations
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Enable server-side encryption for data protection
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      
      # Block all public access for security
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
      # Enable versioning for audit trail purposes
      VersioningConfiguration:
        Status: Enabled

  # EventBridge Scheduled Rule
  # Triggers the Lambda function on a daily schedule
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger SecurityHub SOC 2 analysis daily"
      ScheduleExpression: "cron(0 0 * * ? *)"  # Runs at midnight UTC daily
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt SecurityHubSOC2AnalyzerFunction.Arn
          Id: "SecurityHubSOC2AnalyzerFunction"

  # Lambda Permission for EventBridge
  # Allows EventBridge to invoke the Lambda function
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SecurityHubSOC2AnalyzerFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn

# Template Outputs
# These values are displayed after stack creation for reference
Outputs:
  # Lambda function ARN for reference
  LambdaFunctionArn:
    Description: "ARN of the created Lambda function"
    Value: !GetAtt SecurityHubSOC2AnalyzerFunction.Arn

  # S3 bucket name for accessing reports
  ReportsBucketName:
    Description: "Name of the S3 bucket storing analysis reports"
    Value: !Ref ReportsBucket 