AWSTemplateFormatVersion: '2010-09-09'
Description: SecurityHub SOC 2 Compliance Analyzer - Production Environment

Parameters:
  RecipientEmail:
    Type: String
    Description: Email address for receiving production reports
    Default: security-reports@example.com
  
  FindingsHours:
    Type: Number
    Default: 48
    Description: Number of hours to look back for findings in production
  
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet
    Description: Amazon Bedrock model ID to use for analysis

Resources:
  # Uses the main template with production-specific parameters
  SecurityHubAnalyzerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../template.yaml'
      Parameters:
        RecipientsConfig: !Sub |
          {
            "recipients": [
              {
                "email": "${RecipientEmail}",
                "frequency": "weekly",
                "report_type": ["detailed"]
              },
              {
                "email": "executives@example.com",
                "frequency": "monthly",
                "report_type": ["summary"]
              }
            ]
          }
        FindingsHours: !Ref FindingsHours
        BedrockModelId: !Ref BedrockModelId
      Tags:
        - Key: Environment
          Value: Production

  # CloudWatch Dashboard for monitoring
  SecurityHubDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: SecurityHubSOC2Analyzer-Dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${SecurityHubAnalyzerStack.Outputs.SecurityHubAnalyzerFunctionName}" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "ConcurrentExecutions", "FunctionName", "${SecurityHubAnalyzerStack.Outputs.SecurityHubAnalyzerFunctionName}" ],
                  [ ".", "Throttles", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Concurrency",
                "period": 300
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/${SecurityHubAnalyzerStack.Outputs.SecurityHubAnalyzerFunctionName}' | filter @message like /Error/ | stats count() by bin(30m)",
                "region": "${AWS::Region}",
                "stacked": false,
                "title": "Lambda Errors",
                "view": "timeSeries"
              }
            },
            {
              "type": "text",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 2,
              "properties": {
                "markdown": "## SecurityHub SOC2 Analyzer - Production Dashboard\n\nThis dashboard shows runtime metrics for the SecurityHub SOC2 Analyzer in the Production environment.\n* **Top Row**: Lambda execution metrics\n* **Middle Row**: Error trends\n* **Bottom Row**: Latest findings statistics"
              }
            }
          ]
        }

  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SecurityHub-SOC2-Alerts
      TopicName: SecurityHub-SOC2-Alerts

  # CloudWatch Alarm for Lambda errors
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SecurityHubAnalyzer-Errors
      AlarmDescription: Alarm for SecurityHub SOC2 Analyzer Lambda errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !GetAtt SecurityHubAnalyzerStack.Outputs.SecurityHubAnalyzerFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

Outputs:
  SecurityHubAnalyzerStackName:
    Description: Name of the nested stack
    Value: !Ref SecurityHubAnalyzerStack
  
  LambdaFunctionArn:
    Description: ARN of the created Lambda function
    Value: !GetAtt SecurityHubAnalyzerStack.Outputs.SecurityHubAnalyzerFunctionArn
  
  DashboardURL:
    Description: URL to the CloudWatch Dashboard
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${SecurityHubDashboard}
  
  AlertTopicArn:
    Description: ARN of the SNS Topic for alerts
    Value: !Ref AlertTopic