AWSTemplateFormatVersion: '2010-09-09'
Description: SecurityHub SOC 2 Compliance Analyzer - Staging Environment

Parameters:
  RecipientEmail:
    Type: String
    Description: Email address for receiving reports in staging environment
    Default: staging-alerts@example.com
  
  FindingsHours:
    Type: Number
    Default: 24
    Description: Number of hours to look back for findings
  
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet
    Description: Amazon Bedrock model ID to use for analysis

Resources:
  # Uses the main template with staging-specific parameters
  SecurityHubAnalyzerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../template.yaml'
      Parameters:
        RecipientsConfig: !Sub |
          {
            "recipients": [
              {
                "email": "${RecipientEmail}",
                "frequency": "weekly",
                "report_type": ["detailed", "summary"]
              }
            ]
          }
        FindingsHours: !Ref FindingsHours
        BedrockModelId: !Ref BedrockModelId
      Tags:
        - Key: Environment
          Value: Staging

Outputs:
  StackName:
    Description: Name of the nested stack
    Value: !Ref SecurityHubAnalyzerStack
  
  LambdaFunctionArn:
    Description: ARN of the created Lambda function
    Value: !GetAtt SecurityHubAnalyzerStack.Outputs.SecurityHubAnalyzerFunctionArn